/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hola.myrpc.dubbo.api.dthrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-04-05")
public class MoviePerson implements org.apache.thrift.TBase<MoviePerson, MoviePerson._Fields>, java.io.Serializable, Cloneable, Comparable<MoviePerson> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MoviePerson");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField STAT_DATA_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("statDataList", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MoviePersonStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MoviePersonTupleSchemeFactory();

  public int id; // optional
  public java.util.List<MoviePersonDataDto> statDataList; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    STAT_DATA_LIST((short)2, "statDataList");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // STAT_DATA_LIST
          return STAT_DATA_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.ID, _Fields.STAT_DATA_LIST};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.STAT_DATA_LIST, new org.apache.thrift.meta_data.FieldMetaData("statDataList", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "MoviePersonDataDto"))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MoviePerson.class, metaDataMap);
  }

  public MoviePerson() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MoviePerson(MoviePerson other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetStatDataList()) {
      java.util.List<MoviePersonDataDto> __this__statDataList = new java.util.ArrayList<MoviePersonDataDto>(other.statDataList.size());
      for (MoviePersonDataDto other_element : other.statDataList) {
        __this__statDataList.add(new MoviePersonDataDto(other_element));
      }
      this.statDataList = __this__statDataList;
    }
  }

  public MoviePerson deepCopy() {
    return new MoviePerson(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.statDataList = null;
  }

  public int getId() {
    return this.id;
  }

  public MoviePerson setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getStatDataListSize() {
    return (this.statDataList == null) ? 0 : this.statDataList.size();
  }

  public java.util.Iterator<MoviePersonDataDto> getStatDataListIterator() {
    return (this.statDataList == null) ? null : this.statDataList.iterator();
  }

  public void addToStatDataList(MoviePersonDataDto elem) {
    if (this.statDataList == null) {
      this.statDataList = new java.util.ArrayList<MoviePersonDataDto>();
    }
    this.statDataList.add(elem);
  }

  public java.util.List<MoviePersonDataDto> getStatDataList() {
    return this.statDataList;
  }

  public MoviePerson setStatDataList(java.util.List<MoviePersonDataDto> statDataList) {
    this.statDataList = statDataList;
    return this;
  }

  public void unsetStatDataList() {
    this.statDataList = null;
  }

  /** Returns true if field statDataList is set (has been assigned a value) and false otherwise */
  public boolean isSetStatDataList() {
    return this.statDataList != null;
  }

  public void setStatDataListIsSet(boolean value) {
    if (!value) {
      this.statDataList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Integer)value);
      }
      break;

    case STAT_DATA_LIST:
      if (value == null) {
        unsetStatDataList();
      } else {
        setStatDataList((java.util.List<MoviePersonDataDto>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case STAT_DATA_LIST:
      return getStatDataList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case STAT_DATA_LIST:
      return isSetStatDataList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MoviePerson)
      return this.equals((MoviePerson)that);
    return false;
  }

  public boolean equals(MoviePerson that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_statDataList = true && this.isSetStatDataList();
    boolean that_present_statDataList = true && that.isSetStatDataList();
    if (this_present_statDataList || that_present_statDataList) {
      if (!(this_present_statDataList && that_present_statDataList))
        return false;
      if (!this.statDataList.equals(that.statDataList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetId()) ? 131071 : 524287);
    if (isSetId())
      hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + ((isSetStatDataList()) ? 131071 : 524287);
    if (isSetStatDataList())
      hashCode = hashCode * 8191 + statDataList.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(MoviePerson other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatDataList()).compareTo(other.isSetStatDataList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatDataList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.statDataList, other.statDataList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MoviePerson(");
    boolean first = true;

    if (isSetId()) {
      sb.append("id:");
      sb.append(this.id);
      first = false;
    }
    if (isSetStatDataList()) {
      if (!first) sb.append(", ");
      sb.append("statDataList:");
      if (this.statDataList == null) {
        sb.append("null");
      } else {
        sb.append(this.statDataList);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MoviePersonStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MoviePersonStandardScheme getScheme() {
      return new MoviePersonStandardScheme();
    }
  }

  private static class MoviePersonStandardScheme extends org.apache.thrift.scheme.StandardScheme<MoviePerson> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MoviePerson struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STAT_DATA_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.statDataList = new java.util.ArrayList<MoviePersonDataDto>(_list0.size);
                MoviePersonDataDto _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new MoviePersonDataDto();
                  _elem1.read(iprot);
                  struct.statDataList.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setStatDataListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MoviePerson struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetId()) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeI32(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.statDataList != null) {
        if (struct.isSetStatDataList()) {
          oprot.writeFieldBegin(STAT_DATA_LIST_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.statDataList.size()));
            for (MoviePersonDataDto _iter3 : struct.statDataList)
            {
              _iter3.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MoviePersonTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MoviePersonTupleScheme getScheme() {
      return new MoviePersonTupleScheme();
    }
  }

  private static class MoviePersonTupleScheme extends org.apache.thrift.scheme.TupleScheme<MoviePerson> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MoviePerson struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetStatDataList()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetStatDataList()) {
        {
          oprot.writeI32(struct.statDataList.size());
          for (MoviePersonDataDto _iter4 : struct.statDataList)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MoviePerson struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.statDataList = new java.util.ArrayList<MoviePersonDataDto>(_list5.size);
          MoviePersonDataDto _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new MoviePersonDataDto();
            _elem6.read(iprot);
            struct.statDataList.add(_elem6);
          }
        }
        struct.setStatDataListIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

